### ISSUE TITLE
Suppress loadingpaqes reports caused by malware

### ISSUE THREAD

**Issue by gwire** [report-uri/report-uri-bugs#50] opened 2018-01-11 16:44 UTC
Please add `loadingpaqes.info` to the malware request list.

```
{
    "csp-report": {
        "document-uri": "https://www.example.com/example",
        "referrer": "https://www.google.co.uk/",
        "violated-directive": "script-src https: 'self' data: 'unsafe-inline' 'unsafe-eval'",
        "original-policy": "default-src https: 'self'; font-src https: data:; img-src https: data:; script-src https: 'self' data: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; report-uri https://example.report-uri.io/r/default/csp/reportOnly",
        "blocked-uri": "http://loadingpaqes.info",
        "line-number": 1
    }
}
```

Based on [information elsewhere](https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/explained.md) it appears to be caused by macOS malware.

**Comment by ScottHelme** [comment] 2018-02-11 13:15
Dupe of #42

**Closed by ScottHelme** 2018-02-11 13:15 UTC
Labels: enhancement
