### ISSUE TITLE
Improve viewability of HPKP reports

### ISSUE THREAD

**Issue by notr1ch** [report-uri/report-uri-bugs#31] opened 2017-03-20 14:47 UTC
With the HPKP reports right now, it's rather cumbersome to isolate the bad certificate as you have to manually copy/paste the JSON, decode it, decode the X.509, hash the public key and then compare to the known pins for each cert in the chain.

It would be great if report-uri could implement a JSON decoder and X.509 parser to extract the public key hash and compare it to the known pins, highlighting the failing certificate in some way. As an easier alternative, a one-click "Download .PEM" or similar way to isolate each certificate would help a lot.

**Comment by LordMike** [comment] 2017-03-21 18:32
Didn't @ScottHelme just implement a PEM viewer? :)

**Comment by ScottHelme** [comment] 2017-03-22 10:43
I see what the issue is referring too. It's a lot of work to get the PEM from the report, convert it and then go to the PEM viewer and paste it.

**Comment by ScottHelme** [comment] 2017-11-03 14:15
Given the announced deprecation of HPKP by Chrome I'm going to leave this as won't fix. 

https://scotthelme.co.uk/im-giving-up-on-hpkp/

https://scotthelme.co.uk/the-death-knell-for-hpkp/

**Closed by ScottHelme** 2017-11-03 14:15 UTC
Labels: enhancement
